# Generated by Django 3.2.5 on 2022-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('booksName', models.CharField(max_length=322)),
                ('author', models.CharField(max_length=322)),
                ('publisher', models.CharField(max_length=322)),
            ],
        ),
    ]
