# Generated by Django 3.2.5 on 2022-02-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readersName', models.CharField(max_length=322)),
                ('age', models.CharField(max_length=322)),
            ],
        ),
    ]
