# Generated by Django 3.2.5 on 2022-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_readers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bId', models.CharField(max_length=322)),
                ('bkName', models.CharField(max_length=322)),
                ('rName', models.CharField(max_length=322)),
            ],
        ),
    ]
